"""   Base Tactics for Elenchos

Each tactic is a struct generated by `@tactic` (for the boilerplate) with
its logic in a plain `Tactics.execute` method (for clean stack traces).

Pattern-match on the struct, inspect fields, pipeline with `|>`.
"""
module BaseTactics

using ..Kernel
using ..Tactics
using ..Syntax
using ..Unification: unify, find_first_in_sequent
using ..Walkers: free_variables

export Tactic, TacticFailure, First, resolve_cons, resolve_ante
export start_proof, fwd_axiom, instantiate, fwd_implies_right, rule
export Id, ImpliesRight, ImpliesLeft, NotRight, NotLeft
export ForallRight, ForallLeft
export AndRight, AndLeft, OrRight, OrLeft, Cut, WeakenLeft, WeakenRight
export ArithRight, ArithLeft
export Comm
export Apply, ApplyRule, Exact, Subst, WeakenAllBut, WeakenLeftAllBut, WeakenRightAllBut, Weaken
export id, implies_right, implies_left, not_right, not_left
export forall_right, forall_left
export and_right, and_left, or_right, or_left, cut, weaken_left, weaken_right
export arith_right, arith_left
export comm
export apply, apply_rule, exact, subst, weaken, weaken_all_but, weaken_left_all_but, weaken_right_all_but
export instantiate
export fwd_implies_right, rule

# ═══════════════════════════════════════════════════════════════════════════════
#                         TACTIC DECLARATIONS
# ═══════════════════════════════════════════════════════════════════════════════

@tactic Id()
@tactic ImpliesRight(target_idx::Union{Cons,First,Nothing}=First())
@tactic ImpliesLeft(target_idx::Union{Ante,First,Nothing}=First())
@tactic NotRight(target_idx::Union{Cons,First,Nothing}=First())
@tactic NotLeft(target_idx::Union{Ante,First,Nothing}=First())
@tactic ForallRight(target_idx::Union{Cons,First,Nothing}=First())
@tactic ForallLeft(term::Term, target_idx::Union{Ante,First,Nothing}=First())
@tactic AndLeft(target_idx::Union{Ante,First,Nothing}=First())
@tactic AndRight(target_idx::Union{Cons,First,Nothing}=First())
@tactic OrRight(target_idx::Union{Cons,First,Nothing}=First())
@tactic OrLeft(target_idx::Union{Ante,First,Nothing}=First())
@tactic Cut(formula::Formula, insert_ante::Union{Ante,Nothing}=nothing, insert_cons::Union{Cons,Nothing}=nothing)
@tactic WeakenLeft(fml::Union{Formula,Nothing}=nothing, idx::Union{Ante,Nothing}=nothing)
@tactic WeakenRight(fml::Union{Formula,Nothing}=nothing, idx::Union{Cons,Nothing}=nothing)
@tactic ArithRight(target_idx::Union{Cons,First,Nothing}=First())
@tactic ArithLeft(target_idx::Union{Ante,First,Nothing}=First())
@tactic Comm(target_idx::Union{Cons,First,Nothing}=First())
@tactic Apply(target::Union{Derivation,KernelAxiom}, σ::Union{Substitution,Nothing}=nothing, target_idx::Union{Cons,First,Nothing}=First())
@tactic ApplyRule(rule::Derivation, target_idx::Union{Int,Nothing}=nothing)
@tactic Exact(proof::Derivation)
@tactic Subst(seq::Sequent, σ::Substitution)
@tactic WeakenAllBut(pred::Formula)
@tactic WeakenLeftAllBut(pred::Formula)
@tactic WeakenRightAllBut(pred::Formula)
@tactic Weaken(fml::Formula)
# ═══════════════════════════════════════════════════════════════════════════════
#                         UTILITIES
# ═══════════════════════════════════════════════════════════════════════════════

"""
    generate_fresh_variable(base::Variable, avoid::Set{Variable}) -> Variable

Generate a fresh variable that is not in the `avoid` set.
Uses the base variable's name, appending _1, _2, etc. if needed.
"""
function generate_fresh_variable(base::Variable, avoid::Set{Variable})::Variable
    name = base.name
    if Variable(name) ∉ avoid
        return Variable(name)
    end
    counter = 1
    while true
        candidate = Variable("$(base.name)_$counter")
        if candidate ∉ avoid
            return candidate
        end
        counter += 1
    end
end

# ═══════════════════════════════════════════════════════════════════════════════
#                         EXECUTE METHODS
# ═══════════════════════════════════════════════════════════════════════════════



function Tactics.execute(::Id, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    for (ci, goal) in enumerate(seq.consequent)
        for (ai, hyp) in enumerate(seq.antecedent)
            if hyp == goal
                rule = CloseRule(seq, Ante(ai), Cons(ci))
                return Derivation(p, subgoal_idx, Derivation(rule))
            end
        end
    end
    throw(TacticFailure("No matching hypothesis found"))
end

function Tactics.execute(t::ImpliesRight, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_cons(t.target_idx, seq, f -> f isa Implies)
    insert = Ante(length(seq.antecedent) + 1)
    Derivation(p, subgoal_idx, Derivation(ImpliesRightRule(seq, tidx, insert)))
end

function Tactics.execute(t::ImpliesLeft, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_ante(t.target_idx, seq, f -> f isa Implies)
    insert = Cons(length(seq.consequent) + 1)
    Derivation(p, subgoal_idx, Derivation(ImpliesLeftRule(seq, tidx, insert)))
end

function Tactics.execute(t::NotRight, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_cons(t.target_idx, seq, f -> f isa Not)
    insert = Ante(length(seq.antecedent) + 1)
    Derivation(p, subgoal_idx, Derivation(NotRightRule(seq, tidx, insert)))
end

function Tactics.execute(t::NotLeft, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_ante(t.target_idx, seq, f -> f isa Not)
    insert = Cons(length(seq.consequent) + 1)
    Derivation(p, subgoal_idx, Derivation(NotLeftRule(seq, tidx, insert)))
end

function Tactics.execute(t::ForallRight, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_cons(t.target_idx, seq, f -> f isa Forall)
    goal = seq.consequent[tidx.idx]::Forall
    fresh = generate_fresh_variable(goal.variable, free_variables(seq))
    Derivation(p, subgoal_idx, Derivation(ForallRightRule(seq, tidx, fresh)))
end

function Tactics.execute(t::ForallLeft, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_ante(t.target_idx, seq, f -> f isa Forall)
    fml = seq.antecedent[tidx.idx]::Forall


    inst_formula = Implies(fml, substitute(fml.body, Substitution(fml.variable => t.term)))

    # 1. Cut the implication
    # Subgoal 1: Γ, ∀x. P(x) ⊢ (∀x. P(x)) → P(t), Δ
    # Subgoal 2: Γ, ∀x. P(x), (∀x. P(x)) → P(t) ⊢ Δ

    m = length(seq.antecedent)
    num_cons = length(seq.consequent)

    p = p |> cut(inst_formula; insert_ante=Ante(m + 1), insert_cons=Cons(num_cons + 1), subgoal_idx=subgoal_idx)

    # Subgoal 1 (now at index subgoal_idx):
    # Close it with the axiom
    ax_proof = fwd_axiom(AX_FORALL_INST, _x => fml.variable, _P_sym => fml.body, _y => t.term)
    p = p |> exact(ax_proof; subgoal_idx=subgoal_idx)

    # Subgoal 2 (now at index subgoal_idx):
    # seq2 = Γ, ∀x. P(x), (∀x. P(x)) → P(t) ⊢ Δ
    # Apply ImpliesLeft on the implication
    # Subgoal 2.1: Γ, ∀x. P(x) ⊢ ∀x. P(x), Δ  (Close with Id)
    # Subgoal 2.2: Γ, ∀x. P(x), P(t) ⊢ Δ      (The desired new proof state)

    # We need to resolve the new implication index in the antecedent (it's at m + 1)
    p = p |> implies_left(target_idx=Ante(m + 1), subgoal_idx=subgoal_idx)

    # Subgoal 2.1: Close with identity
    p = p |> Id(subgoal_idx=subgoal_idx)

    return p
end

# ── Defined connectives ──────────────────────────────────────────────────────

function Tactics.execute(t::AndLeft, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_ante(t.target_idx, seq, f -> is_and_pattern(f) !== nothing)

    # A ∧ B = ¬(A → ¬B) — three kernel steps
    step1 = Derivation(NotLeftRule(seq, Ante(tidx.idx), Cons(length(seq.consequent) + 1)))
    seq1 = step1.assumptions[1]
    step2 = Derivation(ImpliesRightRule(seq1, Cons(length(seq1.consequent)), Ante(length(seq1.antecedent) + 1)))
    seq2 = step2.assumptions[1]
    step3 = Derivation(NotRightRule(seq2, Cons(length(seq2.consequent)), Ante(length(seq2.antecedent) + 1)))
    result = Derivation(step1, 1, Derivation(step2, 1, step3))
    Derivation(p, subgoal_idx, result)
end

function Tactics.execute(t::AndRight, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_cons(t.target_idx, seq, f -> is_and_pattern(f) !== nothing)

    step1 = Derivation(NotRightRule(seq, Cons(tidx.idx), Ante(length(seq.antecedent) + 1)))
    seq1 = step1.assumptions[1]
    step2 = Derivation(ImpliesLeftRule(seq1, Ante(length(seq1.antecedent)), Cons(length(seq1.consequent) + 1)))
    seq2 = step2.assumptions[2]
    step3 = Derivation(NotLeftRule(seq2, Ante(length(seq2.antecedent)), Cons(length(seq2.consequent) + 1)))
    result = Derivation(step1, 1, Derivation(step2, 2, step3))
    Derivation(p, subgoal_idx, result)
end

function Tactics.execute(t::OrRight, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_cons(t.target_idx, seq, f -> is_or_pattern(f) !== nothing)

    step1 = Derivation(ImpliesRightRule(seq, Cons(tidx.idx), Ante(length(seq.antecedent) + 1)))
    seq1 = step1.assumptions[1]
    step2 = Derivation(NotLeftRule(seq1, Ante(length(seq1.antecedent)), Cons(length(seq1.consequent) + 1)))
    result = Derivation(step1, 1, step2)
    Derivation(p, subgoal_idx, result)
end

function Tactics.execute(t::OrLeft, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_ante(t.target_idx, seq, f -> is_or_pattern(f) !== nothing)

    # A ∨ B = ¬A → B
    # ImpliesLeft on ¬A → B gives:
    # 1. Γ ⊢ ¬A, Δ
    # 2. Γ, B ⊢ Δ
    step1 = Derivation(ImpliesLeftRule(seq, Ante(tidx.idx), Cons(length(seq.consequent) + 1)))
    seq1_1 = step1.assumptions[1]

    # NotRight on Premise 1 gives: Γ, A ⊢ Δ
    step2 = Derivation(NotRightRule(seq1_1, Cons(length(seq1_1.consequent)), Ante(length(seq1_1.antecedent) + 1)))

    # Combined result
    result = Derivation(step1, 1, step2)
    Derivation(p, subgoal_idx, result)
end


function Tactics.execute(t::Cut, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    ins_ante = if t.insert_ante !== nothing
        t.insert_ante
    else
        Ante(length(seq.antecedent) + 1)
    end
    ins_cons = if t.insert_cons !== nothing
        t.insert_cons
    else
        Cons(length(seq.consequent) + 1)
    end
    Derivation(p, subgoal_idx, Derivation(CutRule(seq, t.formula, ins_cons, ins_ante)))
end


function Tactics.execute(t::WeakenLeft, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    idx = if t.idx !== nothing
        t.idx.idx
    elseif t.fml !== nothing
        findfirst(f -> f == t.fml, seq.antecedent)
    else
        throw(TacticFailure("No target (fml or idx) specified for WeakenLeft"))
    end
    idx === nothing && throw(TacticFailure("Target not found in antecedent: $(t.fml)"))
    return Derivation(p, subgoal_idx, Derivation(WeakeningLeftRule(seq, Ante(idx))))
end

function Tactics.execute(t::WeakenRight, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    idx = if t.idx !== nothing
        t.idx.idx
    elseif t.fml !== nothing
        findfirst(f -> f == t.fml, seq.consequent)
    else
        throw(TacticFailure("No target (fml or idx) specified for WeakenRight"))
    end
    idx === nothing && throw(TacticFailure("Target not found in consequent: $(t.fml)"))
    return Derivation(p, subgoal_idx, Derivation(WeakeningRightRule(seq, Cons(idx))))
end

function Tactics.execute(t::Exact, p::Derivation, subgoal_idx::Int)::Derivation
    Derivation(p, subgoal_idx, t.proof)
end

function exact(ax::KernelAxiom; subgoal_idx=1, σ::Union{Substitution,Nothing}=nothing)
    if σ !== nothing
        exact(fwd_axiom(ax, σ); subgoal_idx=subgoal_idx)
    else
        exact(fwd_axiom(ax); subgoal_idx=subgoal_idx)
    end
end

function Tactics.execute(t::Subst, p::Derivation, subgoal_idx::Int)::Derivation
    instantiated_rule = Derivation(SubstitutionRule(t.seq, t.σ))
    Derivation(p, subgoal_idx, instantiated_rule)
end

function Tactics.execute(t::WeakenAllBut, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    # Weaken antecedent
    ante_to_weaken = [fml for fml in seq.antecedent if fml != t.pred]
    for duplicate in ante_to_weaken
        p = p |> weaken_left(fml=duplicate, subgoal_idx=subgoal_idx)
    end
    # Weaken consequent
    cons_to_weaken = [fml for fml in seq.consequent if fml != t.pred]
    for duplicate in cons_to_weaken
        p = p |> weaken_right(fml=duplicate, subgoal_idx=subgoal_idx)
    end
    return p
end

function Tactics.execute(t::WeakenLeftAllBut, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    # Weaken antecedent
    ante_to_weaken = [fml for fml in seq.antecedent if fml != t.pred]
    for duplicate in ante_to_weaken
        p = p |> weaken_left(fml=duplicate, subgoal_idx=subgoal_idx)
    end
    return p
end

function Tactics.execute(t::WeakenRightAllBut, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    # Weaken consequent
    cons_to_weaken = [fml for fml in seq.consequent if fml != t.pred]
    for duplicate in cons_to_weaken
        p = p |> weaken_right(fml=duplicate, subgoal_idx=subgoal_idx)
    end
    return p
end

function Tactics.execute(t::Weaken, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    # Check antecedent
    idx_ante = findfirst(f -> f == t.fml, seq.antecedent)
    if idx_ante !== nothing
        return Derivation(p, subgoal_idx, Derivation(WeakeningLeftRule(seq, Ante(idx_ante))))
    end

    # Check consequent
    idx_cons = findfirst(f -> f == t.fml, seq.consequent)
    if idx_cons !== nothing
        return Derivation(p, subgoal_idx, Derivation(WeakeningRightRule(seq, Cons(idx_cons))))
    end

    throw(TacticFailure("Formula $(t.fml) not found in sequent"))
end

# ── Arithmetic ────────────────────────────────────────────────────────────────

function Tactics.execute(t::ArithRight, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_cons(t.target_idx, seq, f -> f isa LessThan)
    lt = seq.consequent[tidx.idx]

    # Needs to match the existing context the same way ArithLeft does.
    # GroundInequalityRightRule produces `⊢ a < b`
    current = seq
    weakenings = Derivation[]

    # Remove consequent formulas other than tidx
    adjusted_tidx = tidx.idx
    for j in length(current.consequent):-1:1
        j == adjusted_tidx && continue
        w = Derivation(WeakeningRightRule(current, Cons(j)))
        push!(weakenings, w)
        current = w.assumptions[1]
        if j < adjusted_tidx
            adjusted_tidx -= 1
        end
    end

    # Remove all antecedent formulas
    for j in length(current.antecedent):-1:1
        w = Derivation(WeakeningLeftRule(current, Ante(j)))
        push!(weakenings, w)
        current = w.assumptions[1]
    end

    closed = Derivation(GroundInequalityRightRule(lt.left, lt.right))
    for w in reverse(weakenings)
        closed = Derivation(w, 1, closed)
    end

    Derivation(p, subgoal_idx, closed)
end

function Tactics.execute(t::ArithLeft, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_ante(t.target_idx, seq, f -> f isa LessThan)
    lt = seq.antecedent[tidx.idx]

    # GroundInequalityLeftRule produces a bare  `a < b ⊢`  with no other
    # formulas.  We must weaken away every extra antecedent and every
    # consequent formula so the kernel proof matches the subgoal.
    current = seq
    weakenings = Derivation[]

    # Remove consequent formulas (right-to-left)
    for j in length(current.consequent):-1:1
        w = Derivation(WeakeningRightRule(current, Cons(j)))
        push!(weakenings, w)
        current = w.assumptions[1]
    end

    # Remove antecedent formulas other than tidx (right-to-left, adjusting index)
    adjusted_tidx = tidx.idx  # tracks where our target moved
    for j in length(current.antecedent):-1:1
        j == adjusted_tidx && continue
        w = Derivation(WeakeningLeftRule(current, Ante(j)))
        push!(weakenings, w)
        current = w.assumptions[1]
        if j < adjusted_tidx
            adjusted_tidx -= 1
        end
    end

    # Now current == `a < b ⊢`, which matches GroundInequalityLeftRule output
    closed = Derivation(GroundInequalityLeftRule(lt.left, lt.right))
    for w in reverse(weakenings)
        closed = Derivation(w, 1, closed)
    end

    Derivation(p, subgoal_idx, closed)
end

function Tactics.execute(t::Comm, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    tidx = resolve_cons(t.target_idx, seq, f -> f isa Equals)
    fml = seq.consequent[tidx.idx]

    if (σ = unify(_x + _y ~ _y + _x, fml)) !== nothing
        return p |> apply(instantiate(rule(AX_ADD_COMM), σ); target_idx=tidx, subgoal_idx=subgoal_idx)
    elseif (σ = unify(_x * _y ~ _y * _x, fml)) !== nothing
        return p |> apply(instantiate(rule(AX_MUL_COMM), σ); target_idx=tidx, subgoal_idx=subgoal_idx)
    end

    throw(TacticFailure("Could not match commutativity pattern for goal $(fml)"))
end

function Tactics.execute(t::ApplyRule, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    rule_deriv = t.rule
    isempty(rule_deriv.assumptions) || throw(TacticFailure("Rule must be complete (no open assumptions)"))

    num_rule_cons = length(rule_deriv.conclusion.consequent)
    num_rule_cons <= 1 ||
        throw(TacticFailure("Rule must have at most one formula in consequent"))

    premises = rule_deriv.conclusion.antecedent
    n_prem = length(premises)
    m = length(seq.antecedent)
    num_cons = length(seq.consequent)

    if num_rule_cons == 1
        B = rule_deriv.conclusion.consequent[1]
        tidx = if t.target_idx !== nothing
            t.target_idx
        else
            idx = findfirst(f -> f == B, seq.consequent)
            idx === nothing && throw(TacticFailure("Rule conclusion $B not found in consequent"))
            idx
        end
        1 <= tidx <= num_cons || throw(BoundsError(seq.consequent, tidx))
        seq.consequent[tidx] == B ||
            throw(TacticFailure("Formula at target index doesn't match rule conclusion"))
    else
        tidx = nothing
    end

    # Apply the tactical pipeline explicitly using existing combinators
    for (i, A) in enumerate(premises)
        p = p |> cut(A; insert_ante=Ante(m + i), insert_cons=Cons(num_cons + 1), subgoal_idx=subgoal_idx + i - 1)

        for j in num_cons:-1:1
            p = p |> weaken_right(idx=Cons(j), subgoal_idx=subgoal_idx + i - 1)
        end

        for j in (i-1):-1:1
            p = p |> weaken_left(idx=Ante(m + j), subgoal_idx=subgoal_idx + i - 1)
        end
    end

    final_idx = subgoal_idx + n_prem
    for j in num_cons:-1:1
        if tidx === nothing || j != tidx
            p = p |> weaken_right(idx=Cons(j), subgoal_idx=final_idx)
        end
    end
    for j in m:-1:1
        p = p |> weaken_left(idx=Ante(j), subgoal_idx=final_idx)
    end

    return p |> exact(rule_deriv; subgoal_idx=final_idx)
end

function Tactics.execute(t::Apply, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]

    base = t.target isa KernelAxiom ? rule(t.target) : t.target
    if t.σ !== nothing
        base = instantiate(base, t.σ)
    end

    candidates = t.target isa KernelAxiom ? (base,) : (base, rule(base))
    last_err = nothing

    for cand in candidates
        try
            isempty(cand.assumptions) || throw(TacticFailure("Rule must be complete (no open assumptions)"))
            length(cand.conclusion.consequent) == 1 || throw(TacticFailure("Rule must have exactly one formula in consequent"))

            rule_conclusion = cand.conclusion.consequent[1]
            tidx = resolve_cons(t.target_idx, seq, f -> unify(rule_conclusion, f) !== nothing)
            goal_fml = seq.consequent[tidx.idx]
            σ_unify = unify(rule_conclusion, goal_fml)
            σ_unify === nothing && throw(TacticFailure("Cannot unify rule conclusion $(rule_conclusion) with goal $(goal_fml)"))

            instantiated = instantiate(cand, σ_unify)
            return Tactics.execute(apply_rule(instantiated; target_idx=tidx.idx), p, subgoal_idx)
        catch err
            last_err = err
        end
    end
    if last_err isa Exception
        throw(last_err)
    end
    throw(TacticFailure("Could not apply rule"))
end

# ═══════════════════════════════════════════════════════════════════════════════
#                    FORWARD REASONING (PROOF CONSTRUCTION)
# ═══════════════════════════════════════════════════════════════════════════════
# Functions for building and transforming complete proofs (Derivation values).
# These are *forward* combinators — they compose via `|>` to construct proof
# objects, as opposed to backward tactics which reduce open subgoals.

"""    start_proof(f::Formula) -> Derivation
    start_proof(s::Sequent) -> Derivation

Create an initial proof state from a goal formula or sequent.
"""
start_proof(f::Formula) = Derivation(Assume(Sequent(f)))
start_proof(s::Sequent) = Derivation(Assume(s))

"""    fwd_axiom(ax::KernelAxiom) -> Derivation
    fwd_axiom(ax, σ) -> Derivation
    fwd_axiom(ax, pairs...) -> Derivation

Create and optionally instantiate an axiom.
"""
fwd_axiom(ax::KernelAxiom) = Derivation(AxiomRule(ax))
fwd_axiom(ax::KernelAxiom, σ::Substitution) = instantiate(fwd_axiom(ax), σ)
fwd_axiom(ax::KernelAxiom, pairs::Union{Pair{FunctionSymbol,<:Term},Pair{PredicateSymbol,<:Formula}}...) =
    fwd_axiom(ax, Substitution(pairs...))

"""    instantiate(proof, σ) -> Derivation
    instantiate(proof, pairs...) -> Derivation

Apply a substitution to a complete proof, yielding a new proof with
schematic variables replaced.
"""
function instantiate(proof::Derivation, σ::Substitution)::Derivation
    sub = Derivation(SubstitutionRule(proof.conclusion, σ))
    Derivation(sub, 1, proof)
end

function instantiate(proof::Derivation, pairs::Union{Pair{FunctionSymbol,<:Term},Pair{PredicateSymbol,<:Formula}}...)::Derivation
    instantiate(proof, Substitution(pairs...))
end

"""    fwd_implies_right(proof::Derivation) -> Derivation

Convert a proof of `Γ ⊢ A → B` into a proof of `Γ, A ⊢ B`.

Can be chained to unwrap nested implications:

    fwd_implies_right(fwd_implies_right(fwd_axiom(AX_CONG_PRED, σ)))
    # ⊢ (x=y) → (P(x) → P(y))  ──▶  (x=y), P(x) ⊢ P(y)
"""
function fwd_implies_right(proof::Derivation)::Derivation
    isempty(proof.assumptions) ||
        error("fwd_implies_right: proof must be complete (no open assumptions)")
    length(proof.conclusion.consequent) == 1 ||
        error("fwd_implies_right: proof must have exactly one consequent")
    impl = proof.conclusion.consequent[1]
    impl isa Implies ||
        error("fwd_implies_right: consequent must be an implication, got $(typeof(impl))")

    Γ = proof.conclusion.antecedent
    n = length(Γ)
    A, B = impl.left, impl.right
    goal = Sequent((Γ..., A), (B,))

    # Cut on A → B:  sub1 = Γ, A ⊢ B, A→B  ;  sub2 = Γ, A, A→B ⊢ B
    cut = Derivation(CutRule(goal, impl, Cons(2), Ante(n + 2)))

    # --- Close sub1: Γ, A ⊢ B, A→B ---
    # Weaken away A from antecedent (position n+1), then weaken B from consequent,
    # to reach Γ ⊢ A→B  which matches the original proof's conclusion.
    current = cut.assumptions[1]              # Γ, A ⊢ B, A→B
    wl = Derivation(WeakeningLeftRule(current, Ante(n + 1)))
    # └─ Γ ⊢ B, A→B
    wr = Derivation(WeakeningRightRule(wl.assumptions[1], Cons(1)))
    # └─ Γ ⊢ A→B
    closed_sub1 = Derivation(wl, 1, Derivation(wr, 1, proof))

    # --- Close sub2: Γ, A, A→B ⊢ B ---
    # ImpliesLeft on A→B (position n+2):
    #   branch 1 = Γ, A ⊢ B, A  ;  branch 2 = Γ, A, B ⊢ B
    il = Derivation(ImpliesLeftRule(cut.assumptions[2], Ante(n + 2), Cons(length(cut.assumptions[2].consequent))))
    close_a = Derivation(CloseRule(il.assumptions[1], Ante(n + 1), Cons(1)))
    close_b = Derivation(CloseRule(il.assumptions[2], Ante(n + 2), Cons(1)))
    closed_sub2 = Derivation(Derivation(il, 1, close_a), 1, close_b)

    # Combine
    Derivation(Derivation(cut, 1, closed_sub1), 1, closed_sub2)
end

"""    rule(ax, σ) -> Derivation
    rule(ax, pairs...) -> Derivation
    rule(ax) -> Derivation

Instantiate a conditional axiom and convert to rule normal form by
repeatedly assuming premises.

    ⊢ A → (B → C)   ──rule──▶   A, B ⊢ C

Examples:

    rule(AX_CONG_PRED, _x_sym => a, _y_sym => b, _P_sym => ctx)
    #   ⊢ (a=b) → (P(a) → P(b))   ──▶   (a=b), P(a) ⊢ P(b)
"""
function rule(ax::KernelAxiom, args...)::Derivation
    proof = fwd_axiom(ax, args...)
    return rule(proof)
end

function rule(proof::Derivation, args...)::Derivation
    while !isempty(proof.conclusion.consequent) && proof.conclusion.consequent[1] isa Implies
        proof = fwd_implies_right(proof)
    end
    return proof
end

# ═══════════════════════════════════════════════════════════════════════════════
#                         TERM ORDERING
# ═══════════════════════════════════════════════════════════════════════════════

"""
    term_lt(a::Term, b::Term) -> Bool

Total order on terms for canonical sorting of commutative sums/products.

Ordering: Constants < Variables (by name) < compound terms (by constructor tag,
then lexicographically by children).
"""
function term_lt(a::Term, b::Term)
    ta, tb = _term_tag(a), _term_tag(b)
    ta != tb && return ta < tb
    _term_lt_same_tag(a, b)
end

# Assign numeric tags for top-level ordering
_term_tag(::Constant) = 0
_term_tag(::Variable) = 1
_term_tag(::FunctionApplication) = 2
_term_tag(::Sum) = 3
_term_tag(::Difference) = 4
_term_tag(::Product) = 5
_term_tag(::Division) = 6
_term_tag(::Power) = 7
_term_tag(::Hole) = 8

# Same-tag comparison
_term_lt_same_tag(a::Constant, b::Constant) = a.value < b.value
_term_lt_same_tag(a::Variable, b::Variable) = a.name < b.name

function _term_lt_same_tag(a::FunctionApplication, b::FunctionApplication)
    a.symbol.name != b.symbol.name && return a.symbol.name < b.symbol.name
    _lex_lt(a.arguments, b.arguments)
end

function _term_lt_same_tag(a::T, b::T) where T<:Union{Sum,Difference,Product,Division}
    a.left != b.left && return term_lt(a.left, b.left)
    term_lt(a.right, b.right)
end

function _term_lt_same_tag(a::Power, b::Power)
    a.base != b.base && return term_lt(a.base, b.base)
    term_lt(a.exponent, b.exponent)
end

_term_lt_same_tag(a::Hole, b::Hole) = a.index < b.index

function _lex_lt(as, bs)
    for (a, b) in zip(as, bs)
        a != b && return term_lt(a, b)
    end
    length(as) < length(bs)
end

export term_lt

# ─────────────────────────────────────────────────────────────────────────────
#                       ORDERING FUNCTORS
# ─────────────────────────────────────────────────────────────────────────────

abstract type Order end
struct NoOrder <: Order end
struct TermOrder <: Order end
struct MonomialOrder <: Order end

"""
    split_coeff(t::Term) -> (Constant, Term)

Split a summand into (coefficient, monomial_body).
After right-association of products the coefficient is the leftmost factor
when it is a Constant; otherwise the implicit coefficient is 1.
"""
function split_coeff(t::Term)::Tuple{Constant,Term}
    if t isa Product && t.left isa Constant
        return (t.left, t.right)
    end
    return (ONE, t)
end

"""
    monomial_lt(a::Term, b::Term) -> Bool

Lexicographic monomial order for sorting summands in a polynomial.
Strips leading numeric coefficients and compares monomial bodies via
`term_lt`; ties are broken by coefficient.
Sums are compared recursively by their head summand.
"""
function monomial_lt(a::Term, b::Term)::Bool
    # Recursive comparison for right-associated sums
    if a isa Sum && b isa Sum
        return a.left == b.left ? monomial_lt(a.right, b.right) : monomial_lt(a.left, b.left)
    end

    # A non-sum is always "smaller" than a sum (atoms sort before tails)
    a isa Sum && return false
    b isa Sum && return true

    # Compare individual summands by monomial body, then coefficient
    ca, ma = split_coeff(a)
    cb, mb = split_coeff(b)

    return ma == mb ? term_lt(ca, cb) : term_lt(ma, mb)
end

# Functor interface: (order)(lower, higher) -> Bool
# Strongly typed to prevent dynamic dispatch when called inside the unification loop
(::NoOrder)(a::Term, b::Term) = true
(::TermOrder)(a::Term, b::Term) = term_lt(a, b)
(::MonomialOrder)(a::Term, b::Term) = monomial_lt(a, b)

# ─────────────────────────────────────────────────────────────────────────────
#                         REWRITE TACTIC (Unified & Optimized)
# ─────────────────────────────────────────────────────────────────────────────

struct FindTarget{T<:Union{SequentPosition,First,Nothing},O<:Order}
    pattern::Term
    pos::T
    order::O
end

struct ExactSubterm{T<:Union{SequentPosition,First,Nothing}}
    pos::T
    path::Vector{Int}
end

struct ExactMatch{T<:Union{SequentPosition,First,Nothing}}
    pattern::Term
    pos::T
end

function resolve_site(loc::ExactMatch, seq::Sequent, replacement::Term)
    search_pos = loc.pos isa First ? nothing : loc.pos
    site = find_first_in_sequent(seq; pos=search_pos) do term
        term == loc.pattern ? Substitution() : nothing
    end
    if site === nothing
        pos_info = loc.pos === nothing ? "" : " at position $(loc.pos)"
        throw(TacticFailure("Pattern $(loc.pattern) not found$pos_info with ExactMatch in sequent.\n$seq"))
    end
    _, ctx = site.data
    return loc.pattern, replacement, ctx, site.pos
end

function resolve_site(loc::FindTarget, seq::Sequent, replacement::Term)
    check_order = !(loc.order isa NoOrder)
    search_pos = loc.pos isa First ? nothing : loc.pos
    site = find_first_in_sequent(seq; pos=search_pos) do term
        σ = unify(loc.pattern, term)
        σ === nothing && return nothing
        !check_order || loc.order(substitute(replacement, σ), substitute(loc.pattern, σ)) ? σ : nothing
    end
    if site === nothing
        pos_info = loc.pos === nothing ? "" : " at position $(loc.pos)"
        throw(TacticFailure("Pattern $(loc.pattern) not found$pos_info with $(typeof(loc.order)) in sequent.\n$seq"))
    end
    σ, ctx = site.data
    return σ(loc.pattern), σ(replacement), ctx, site.pos
end

using ..Walkers: path_context
function resolve_site(loc::ExactSubterm, seq::Sequent, replacement::Term)
    pos = loc.pos
    if pos isa First || pos === nothing
        pos = Cons(1)
    end
    fml = pos isa Ante ? seq.antecedent[pos.idx] : seq.consequent[pos.idx]
    ctx, old = path_context(fml, loc.path)
    return old, replacement, ctx, pos
end

struct Rewrite{L} <: Tactics.Tactic
    replacement::Term
    loc::L
    subgoal_idx::Union{Int,Nothing}
end

# User APIs
rewrite(replace::Pair; seq_pos::Union{SequentPosition,First,Nothing}=First(), order::Order=NoOrder(), subgoal_idx=1) =
    Rewrite(convert(Term, replace.second), FindTarget(convert(Term, replace.first), seq_pos, order), subgoal_idx)

rewrite(replace::Pair, ::Type{ExactMatch}; seq_pos::Union{SequentPosition,First,Nothing}=First(), subgoal_idx=1) =
    Rewrite(convert(Term, replace.second), ExactMatch(convert(Term, replace.first), seq_pos), subgoal_idx)

rewrite(replacement::Term, seq_pos::SequentPosition, path::Vector{Int}; subgoal_idx=1) =
    Rewrite(replacement, ExactSubterm(seq_pos, path), subgoal_idx)

rewrite(replacement::Term, path::Vector{Int}; subgoal_idx=1) =
    Rewrite(replacement, ExactSubterm(Cons(1), path), subgoal_idx)

rewrite_left(term::Term, seq_pos::SequentPosition; kwargs...) = rewrite(term, seq_pos, [1]; kwargs...)
rewrite_left(term::Term; kwargs...) = rewrite(term, [1]; kwargs...)

rewrite_right(term::Term, seq_pos::SequentPosition; kwargs...) = rewrite(term, seq_pos, [2]; kwargs...)
rewrite_right(term::Term; kwargs...) = rewrite(term, [2]; kwargs...)

Base.show(io::IO, r::Rewrite) = print(io, "rewrite")

function (t::Rewrite)(p::Derivation, subgoal_idx::Int)
    n = length(p.assumptions)
    1 <= subgoal_idx <= n || throw(Tactics.TacticFailure("Subgoal $subgoal_idx out of bounds ($n open)"))
    Tactics.execute(t, p, subgoal_idx)
end

function Tactics.execute(t::Rewrite, p::Derivation, subgoal_idx::Int)::Derivation
    seq = p.assumptions[subgoal_idx]
    old_term, new_term, ctx, pos = resolve_site(t.loc, seq, t.replacement)

    if pos isa Cons
        ν = Substitution(_P_sym => ctx, _x_sym => new_term, _y_sym => old_term)
        return p |> apply(instantiate(rule(AX_CONG_PRED), ν); target_idx=pos, subgoal_idx=subgoal_idx)
    else
        η = Substitution(1 => new_term)
        new_fml = substitute(ctx, η)
        idx_cons = Cons(length(seq.consequent) + 1)
        p = p |> cut(new_fml; subgoal_idx=subgoal_idx, insert_cons=idx_cons)

        ν_b = Substitution(_P_sym => ctx, _x_sym => old_term, _y_sym => new_term)
        p = p |> apply(instantiate(rule(AX_CONG_PRED), ν_b); target_idx=idx_cons, subgoal_idx=subgoal_idx)

        # Close the P(old_term) branch which is now at subgoal_idx + 1
        p = p |> id(subgoal_idx=subgoal_idx + 1)

        # Weaken old_fml from the assumed new_fml branch, now at subgoal_idx + 1 again
        fml_old = pos isa Ante ? seq.antecedent[pos.idx] : seq.consequent[pos.idx]
        p = p |> weaken_left(fml=fml_old; subgoal_idx=subgoal_idx + 1)
        
        return p
    end
end

export Order, NoOrder, TermOrder, MonomialOrder, monomial_lt
export FindTarget, ExactMatch, ExactSubterm, Rewrite, rewrite, rewrite_left, rewrite_right

end # module BaseTactics
